### PR TITLE
Replace get-pixels with ndarray-pixels

### PR DESCRIPTION
**Pull request by briandonahue**
Addresses #246. In looking into that issue, I found [this comment](https://github.com/scijs/get-pixels/issues/62#issuecomment-1590386919) on `get-pixels`. [ndarray-pixels](https://github.com/donmccurdy/ndarray-pixels) relies on `sharp` and has been more recently maintained.  

I updated `color-thief` to use it instead of `get-pixels` and all tests are passing. Hope this helps somebody!

### CODE REVIEW

**Comment by maiconcarraro** [comment]
@lokesh plans to merge this? and is it possible to buy you a coffee or sponsor to keep this project healthy?

**Comment by nathanchase** [comment]
@briandonahue Is there a possibility of pushing https://github.com/briandonahue/color-thief to npm in the meantime?

**Comment by briandonahue** [comment]
@nathanchase I didn't end up using colorthief in production (yet). Held off on the planned feature. I'm pretty swamped and have not pushed any public NPM packages.  Anyone who wants to take my fork and publish a package is welcome to, though.

**Comment by maiconcarraro** [comment]
I'm using https://github.com/pioug/colorsuite until I find a better replacement

**Comment by jp-albrecht** [comment]
@lokesh, any update on whether this will get merged in?

**Comment by lokesh** [comment]
Had some merge conflicts so created a new PR to merge in your changes. 🙏

https://github.com/lokesh/color-thief/releases/tag/v2.6.0

**Pull request closed without merging**
