### PR TITLE
Add node support

### PR DESCRIPTION
**Pull request by jo**
with tests and readme notes.

### CODE REVIEW

**Comment by ksubileau** [comment]
Why did you close this issue, @jo ? Is it fixed ?

**Comment by jo** [comment]
sorry, it has been so long open ;)

**Comment by jo** [comment]
(should have stated this)

**Comment by ksubileau** [comment]
It's true that it's quite old, but it's still interesting ! Maybe someday... :)

**Comment by jo** [comment]
:)

**Comment by josephmilla** [comment]
Please?

**Comment by lokesh** [comment]
Node support now exists in the mainline for the project:
https://github.com/lokesh/color-thief#how-to-use-color-thief-in-node

Went a different route than null2's fork which used the canvas package. Opted to use `get-pixel` for a js only solution.

**Pull request closed without merging**
