### PR TITLE
ENHANCEMENT : HEX Color Array Option : i.e. #0F0F0F

### PR DESCRIPTION
**Pull request by zamartz**
Allows the Colors to be sent in HEX values instead of RGB

### CODE REVIEW

**Comment by pierrebonbon** [comment]
Hi, great feature enhancement. What still needs to be done?

**Comment by zamartz** [comment]
@pierrebonbon nothing needs to be done - just needs the updated portions to be merged into main branch. You can merge with your current version and use accordingly with the updated ReadMe that I included as well.

**Comment by pierrebonbon** [comment]
@zamartz Great, thanks! Btw, why did you choose that specific function for the conversion in place of any other?

**Comment by zamartz** [comment]
@pierrebonbon I chose this function because it uses the least number of calls. It basically takes the core functionality and processes the return values to be what format you want. This edit would allow for further formatting/conversion such as making colors in gamut or websafe.

**Comment by pierrebonbon** [comment]
Thanks for the thorough explanation. Further conversion would be quite convenient. Btw, I've resorted before to a single line function that relies heavily on the left shift operator, which is perhaps fast, but doesn't allow for much if any extensibility. It's good for the sole purpose of a specific conversion job I guess.

**Comment by keshavnaidu** [comment]
@zamartz How to print hex value in my pallet {{#palette}}

**Comment by zamartz** [comment]
@keshavnaidu  you would only send the 6 digit HEX value, you would not prefix with "#" as the "ctype" = "hex" would assume it is not needed. You would want to eliminate special characters to not confuse the system and keep the code short.

**Comment by zamartz** [comment]
@lokesh  please merge

**Comment by zamartz** [comment]
Closing via = https://github.com/lokesh/color-thief/issues/116
This is not integrated into the core functionality but a conversion function is added to the Wiki

**Pull request closed without merging**
